# Generated by Django 6.0.7 on 2026-07-12 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_file', models.FileField(upload_to='documents/original/')),
                ('encrypted_file', models.FileField(blank=True, null=True, upload_to='documents/encrypted/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ENCRYPTED', 'Encrypted')], default='PENDING', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('encrypted_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
