# Generated by Django 6.0.7 on 2026-07-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_file', models.FileField(upload_to='documents/original/')),
                ('encrypted_file', models.FileField(blank=True, null=True, upload_to='documents/encrypted/')),
                ('encrypted_key', models.BinaryField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ENCRYPTED', 'Encrypted')], db_index=True, default='PENDING', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('encrypted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
