# Generated by Django 6.0.7 on 2026-07-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='encrypted_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
