# Generated by Django 6.0.7 on 2026-07-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='original_file',
            field=models.FileField(blank=True, max_length=255, upload_to='documents/original/'),
        ),
    ]
