# Generated by Django 6.0.7 on 2026-07-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=25, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('programme', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('year_of_study', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEFERRED', 'Deferred'), ('GRADUATED', 'Graduated')], default='ACTIVE', max_length=25)),
            ],
        ),
    ]
