# Generated by Django 6.0.7 on 2026-08-03 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 3, 15, 21, 41, 641780, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
