# Generated by Django 6.0.7 on 2026-07-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DEFERRED', 'Deferred'), ('GRADUATED', 'Graduated'), ('DEACTIVATED', 'Deactivated')], default='ACTIVE', max_length=25),
        ),
    ]
