# Generated by Django 6.0.7 on 2026-08-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('REGISTER', 'Register'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Update'), ('UPLOAD', 'Upload'), ('DOWNLOAD', 'Download'), ('PREVIEW', 'Preview'), ('PASSWORD_CHANGE', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('ACCOUNT_ACTIVATED', 'Account Activated'), ('ACCOUNT_EDITED', 'Account Edited'), ('ACCOUNT_DEACTIVATED', 'Account Deactivated')], max_length=50),
        ),
    ]
